### ISSUE TITLE
Map not playing [portal changed date format]

### ISSUE THREAD

**Issue by PLNReynolds** [datalab-dev/covid_worksite_exposure#19]
Map appears but no data (current or historical) displays. First noticed on 10/1/2021. Issue appears on both the blog post embedding and at https://datalab-dev.github.io/covid_worksite_exposure/.

**Comment by t-shoemaker** [comment]
I suspect this is a problem with datetime formats. Looks like the exposure site has changed how it displays dates.

Old format:
<img width="310" alt="Screen Shot 2021-10-01 at 5 17 35 PM" src="https://user-images.githubusercontent.com/69219954/135697668-e155c776-d9f2-488d-a4ef-bb75d9284c16.png">

New format:
<img width="310" alt="Screen Shot 2021-10-01 at 5 17 31 PM" src="https://user-images.githubusercontent.com/69219954/135697672-f0d0111e-096f-4793-815c-88c786981e2e.png">

**Comment by PLNReynolds** [comment]
Tagging @erklopez and @elistockwell in case you are working this weekend and can tackle this while Michele is recovering from virtual conference jet lag. :) Code chunk to modify starts on line 209 of scrape_exposure_data.R.

**Comment by t-shoemaker** [comment]
I have a fix on this in a new branch called `datetime_quick_fix`, but it's super messy and I'm not going to bother opening a pull request for it. Jared and I were able to get the correct data uploaded to the DataLab site for now, so at the very least anyone who visits the site won't see a problem. Ideally though what I've pushed to the new branch should be refactored, as it itself is a little brittle when it comes to the datetime formatting.

**Comment by MicheleTobias** [comment]
It would have been nice to be pinged about this on slack. I'll lot into it.

**Comment by MicheleTobias** [comment]
The quick fix only works as long as the github action doesn't run and set it back to the data on the site. I'll trim the bad data out for now and turn off the action until we can fix it on Monday. 

@elistockwell & @erklopez you don't need to work on this over the weekend. If either of you has time on Monday morning, send me a slack message and we'll figure out how we can tag-team this fix.

**Comment by t-shoemaker** [comment]
Quick clarification: the DataLab site is now using a static version of the map since, as you say, Michele, the action would just erase the fix. So we'll need to switch that back next week, but luckily the exposure data isn't updated over the weekend so a static instance will do.

**Comment by MicheleTobias** [comment]
Regardless, I disabled the GitHub action and rolled back the data on the map to Thursday's data so the actual map works in case anyone finds it that way or clicks through to the GitHub repo from the blog post.  On Monday I'll deal with the dates and removing the duplicates it introduced.

**Comment by MicheleTobias** [comment]
I wrote #20 to clarify this issue and identify the steps we need to take so I'm closing this one.
