### ISSUE TITLE
Github link does not work from datalab website

### ISSUE THREAD

**Issue by CRiddler** [datalab-dev/covid_worksite_exposure#23]
Clicking on the github link from the map on the datalab website does not redirect the users browser to github. It instead redirects the iframe, which ends up breaking.

| Before clicking github link | After clicking on the github link |
| ----------------------------  | ---------------------------------- |
|  ![image](https://user-images.githubusercontent.com/31414128/138185988-59154367-9395-4d83-9ef6-8b42bbeec4fc.png) | ![image](https://user-images.githubusercontent.com/31414128/138185433-16e4cead-29a1-43b5-a1a4-9ca310db5b01.png) | 

[Current implementation](https://github.com/datalab-dev/covid_worksite_exposure/blob/8c8a1230445d525f700b55be0c3f36e1989e33e9/docs/index.html#L168)
```
<a href="https://github.com/datalab-dev/covid_worksite_exposure">GitHub</a>
```

The easiest workaround will be to use the `target` attribute of the anchor tag:
* `target="_top"` Redirects in the outermost frame (the users web browser), instead of the iframe
* `target="_blank"` Redirect to occurs in a new tab, circumventing the issue.

Suggestion:
```
<a href="https://github.com/datalab-dev/covid_worksite_exposure" target="_top">GitHub</a>
```

Browser: Microsoft Edge

**Comment by MicheleTobias** [comment]
Thanks for your help with this! I believe it's fixed now and the link opens in a new tab rather than in the iframe on the DataLab website.
