### ISSUE TITLE
Campus Website Format Change

### ISSUE THREAD

**Issue by MicheleTobias** [datalab-dev/covid_worksite_exposure#33]
As of 2/25/2022, in the `scrape_exposure_data.r` script, the table we scrape from the Potential Covid Exposures page has some extra (blank) columns that's throwing off the script - it has a column called "sort ascending", for example.  The `covid_df_pages` variable is the wrong number of columns so it throws an error on line 58.  I suspect that something changed on the website (maybe a sorting feature got added) that's causing this. Let's see if it continues to be a problem, and if it's not back to normal by around mid-week, let's adjust the code.

**Comment by erklopez** [comment]
Fixed with pull request #34
