### ISSUE TITLE
Is this open source?

### ISSUE THREAD

**Issue by vmx** [datalab-dev/covid_worksite_exposure#35]
This looks like the source code of a submission for the FOSS4G 2022. It would be great if this would be open source. If it is, please at a license.

**Comment by MicheleTobias** [comment]
Yes, it is open source. The team is debating which specific license to put here, but it will be open. I'll update when I get this resolved - hopefully by tomorrow.

**Comment by MicheleTobias** [comment]
We decided on the MIT license for the code. I added the license file to the repo so it should be clear now.
